### ISSUE TITLE
Style must be in LESS files, not in code

### ISSUE THREAD

**Issue by Kendos-Kenlen** [alanzanattadev/atom-molecule-dev-environment#125]
Currently, we put a lot of style directly into presenters or in the code.
We need to move it to LESS files (maybe one file per Epic or per Feature) in order to have a more unified style and, when change are needed, not having to look all around the code to find an obsolete style.

It would simplify maintaining of the code and allow a better reusability of styles.

**Comment by alanzanattadev** [comment]
Some styles like colors and theme dependant metrics have to be in less yes, but not all, because we have to use js to make dynamic styles
