### ISSUE TITLE
Poping empty stash should not be possible

### ISSUE THREAD

**Issue by Kendos-Kenlen** [alanzanattadev/atom-molecule-dev-environment#144]
If the git' stash is empty, the button to pop should be empty to avoid confusion.

Also, the error message contains 2 times the "No stash found" line.

```
Error: Command failed: git stash pop
No stash found.
No stash found.
```

**Comment by lorenzoalfieri** [comment]
Disabling versionning panel #205 .
Since atom is doing a git integration in 1.18, we  don't need it anymore.
