### ISSUE TITLE
Eslint have an error on each end of line on Windows

### ISSUE THREAD

**Issue by lorenzoalfieri** [alanzanattadev/atom-molecule-dev-environment#146]

**Comment by Kendos-Kenlen** [comment]
This isn't an Eslint issue, but a git one.
We want Molecule to use Unix line breaks, but on Windows, git automatically convert Unix line breaks to Windows ones and vis-versa when committing to ensure a correct behavior with editors on Windows.

You can disable this behavior in git. [Eslint doc](http://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems) explains how to do this.
