### ISSUE TITLE
Replace eslint with prettier

### ISSUE THREAD

**Issue by quentin-sommer** [alanzanattadev/atom-molecule-dev-environment#159]
Hi,

I think it would be nice for this project to use [prettier](https://github.com/prettier/prettier) for its code formatting, especially since there are a lot of inline nested functions with several styles at the moment. The overall clarity would be vastly improved!

**Comment by alanzanattadev** [comment]
Hi,

The project already use prettier :) ESLint is here to detect code not prettified :)

**Comment by quentin-sommer** [comment]
Oh right, hadn't seen you were using the eslint prettier plugin!
