### ISSUE TITLE
Warnings when launch yarn test

### ISSUE THREAD

**Issue by Newtchuck** [alanzanattadev/atom-molecule-dev-environment#178]
**console.error node_modules/fbjs/lib/warning.js:36**
      Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
**console.error node_modules/fbjs/lib/warning.js:36**
      Warning: Shallow renderer has been moved to react-test-renderer/shallow. Update references to remove this warn
**console.error node_modules/fbjs/lib/warning.js:36**
      Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by PoignardAzur** [comment]
Should be closed.
