### ISSUE TITLE
Flow plugin broken

### ISSUE THREAD

**Issue by alanzanattadev** [alanzanattadev/atom-molecule-dev-environment#210]

**Comment by Kendos-Kenlen** [comment]
The plugin is broken for 2 reason: 

 - The API is out dated, we have to update the plugin to comply to the current architecture (use onData).
- The plugin doesn't receive a full and valid JSON file. The content is cut before the end.
When looking into the console, we can see a promise which fails without any error. i tried to reproduce in a bash terminal, and when started with `yarn flow`, the problem also occurs. I suspect the problem not coming from Molecule itself.
