### ISSUE TITLE
Method `onNewPlan` in ControlPanel is never used

### ISSUE THREAD

**Issue by PoignardAzur** [alanzanattadev/atom-molecule-dev-environment#424]
The method `onNewPlan`: https://github.com/alanzanattadev/atom-molecule-dev-environment/blob/master/lib/ExecutionControlEpic/ControlPanelFeature/Containers/Panel.js#L203

Is never called anywhere. Instead, the plan configurer is opened in "Presenters/ContentPanel.js" under `case "plan-config":`.

**Comment by GauthierPLM** [comment]
Should be fixed in last release (v1.1).
