### ISSUE TITLE
Style of search box in diagnostic

### ISSUE THREAD

**Issue by giardb** [alanzanattadev/atom-molecule-dev-environment#428]
![capture d ecran 2018-09-25 a 14 50 10](https://user-images.githubusercontent.com/9026408/46015689-32efaa00-c0d3-11e8-89aa-76a46962c7d4.png)

Doesn't fit the style and the icon is outside the box.

Style Used:
- UI theme: Atom Material
- Syntax Theme: Atom Material Dark

**Comment by GauthierPLM** [comment]
Should be fixed in last release (v1.1).
