### ISSUE TITLE
Unable to install this thing on Windows 

### ISSUE THREAD

**Issue by OstapKryvytskyy** [alanzanattadev/atom-molecule-dev-environment#475]
Currently it not available to install easily on windows due to dependency for MacOs native fsevents and skipping all the installation beforehand.

**Comment by GauthierPLM** [comment]
Hello,

`fsevents` is a library which allows us to monitor file system changes in your projects (when you save or add a file for example) on MacOS and Windows. `node-gyp` is node native build system and is required to build fsevents.

You can find the instructions to install node-gyp [here](https://github.com/nodejs/node-gyp#on-windows). Once you have it installed, you will be able to install Molecule without any issue.

If you need more help, feel free to reopen this issue.

Best regards,
-- Gauthier
